
@startuml
title Board Model's status



state Manageable {
  Public   : 公開中
  Unpublic : 未公開
}

state Unmanaged {
  Removed : Owner/Admin deleted board
}

[*]      -down-> Unpublic : [O]掲示板の作成
Unpublic -down-> Public : [O]
Public   -up-> Unpublic : [O]

Manageable --> Removed : [O/A]

legend
- S : System
- A : Server Admin
- O : Owner
- U : User
- G : Guest
end legend

@enduml