
@startuml
title Board Model's status



state Normal{
  Public   : 公開中
  Unpublic : 未公開
}

state Abnormal{
  Ban    : Admin banned board.
  Delete : User deleted board by self.
}

[*]      -down-> Unpublic : [S]掲示板の作成
Unpublic -down-> Public : [O]
Public   -up-> Unpublic : [O]

Normal --> Ban : [A]
Normal --> Delete : [O]

legend
- S : System
- A : Server Admin
- O : Owner
- U : User
- G : Guest
end legend

@enduml